---

- name: enable passwordless sudo access
  shell: echo '%adm ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/admins
  #lineinfile: "dest=/etc/sudoers state=present regexp='^%adminl' line='%admin ALL=(ALL) NOPASSWD: ALL'"
  tags:
    - sudo


- name: disable IPv6 forwarding
  lineinfile:
    path: /etc/sysctl.conf
    line: "{{item}}"
  with_items:
    - "net.ipv6.conf.all.disable_ipv6 = 1"
    - "net.ipv6.conf.default.disable_ipv6 = 1"
  tags:
    - disable_ipv6

- name: sysctl -p
  shell: sysctl -p
  tags:
    - sysctl_reload

- name: disable ufw
  service: name=ufw state=stopped enabled=no
  ignore_errors: true


- name: apt-get update
  apt:
    update_cache: yes
  tags:
    - apt_update


- name: install prereq packages
  apt:
    name: tar,xz,zip,unzip,curl,ipset,bzip2,lldpad,net-tools,bind-utils
    state: present
  ignore_errors: true
  tags:
    - packages


- name: install contiv prereq packages
  apt:
    name: ansible,bzip2,python-netaddr,git,python-pip
    state: present
  ignore_errors: true
  tags:
    - packages


- name: update SElinux
  shell: sudo sed -i s/SELINUX=enforcing/SELINUX=permissive/g /etc/selinux/config
  tags:
    - update_selinux

- name: setenforce 0
  shell: setenforce 0
  tags:
    - update_selinux
# - name: setenforce 0
#   shell: setenforce 0
#   when: ansible_distribution == 'CentOS'
