---

- name: add admin file
  file:
    path: /etc/sudoers.d/admins
    state: touch
  tags:
    - admin_file


- name: enable passwordless sudo access
  lineinfile:
    path: /etc/sudoers.d/admins
    line: "{{item}}"
  with_items:
    - "%adm ALL=(ALL) NOPASSWD:ALL"
  ignore_errors: true
  tags:
    - sudo


- name: disable IPv6 forwarding
  lineinfile:
    path: /etc/sysctl.conf
    line: "{{item}}"
  with_items:
    - "net.ipv6.conf.all.disable_ipv6 = 1"
    - "net.ipv6.conf.default.disable_ipv6 = 1"
  tags:
    - disable_ipv6


- name: sysctl -p
  shell: sysctl -p
  tags:
    - sysctl_reload


- name: disable ufw 
  systemd:
    state: stopped
    enabled: no
    daemon_reload: no
    name: ufw
  tags:
    - stop_firewall


- name: apt-get update
  apt:
    update_cache: yes
  tags:
    - apt_update


- name: install prereq packages
  apt:
    name: ifenslave,bzip2,tar,zip,unzip,curl,ipset,lldpad,net-tools
    state: present
  ignore_errors: true
  tags:
    - packages


- name: install contiv prereq packages
  apt:
    name: python-netaddr,git,python-pip
    state: present
  ignore_errors: true
  tags:
    - packages


